export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const SET_COMMENT_SORTING = 'SET_COMMENT_SORTING';
export const COMMENT_VOTE = 'COMMENT_VOTE';
