export const Sorting = {
  BY_DATE_NEWEST: 'BY_DATE_NEWEST',
  BY_DATE_OLDEST: 'BY_DATE_OLDEST',
  BY_SCORE_HIGHEST: 'BY_SCORE_HIGHEST',
  BY_SCORE_LOWEST: 'BY_SCORE_LOWEST',
};

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
